const ShopActionTypes = {
	FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START', 
	FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS', 
	FETCH_COLLECTIONS_FAIURE: 'FETCH_COLLECTIONS_FAIURE'
}

export default ShopActionTypes